// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboards.sql

package gensql

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createPublicDashboard = `-- name: CreatePublicDashboard :one
INSERT INTO metabase_dashboard (
    name,
    description,
    "group",
    public_dashboard_id,
    metabase_id,
    created_by,
    keywords,
    teamkatalogen_url
) 
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
) RETURNING id, name, description, "group", public_dashboard_id, metabase_id, created_by, created, last_modified, tsv_document, keywords, teamkatalogen_url
`

type CreatePublicDashboardParams struct {
	Name              string
	Description       sql.NullString
	OwnerGroup        string
	PublicDashboardID uuid.UUID
	MetabaseID        int32
	CreatedBy         string
	Keywords          []string
	TeamkatalogenUrl  sql.NullString
}

func (q *Queries) CreatePublicDashboard(ctx context.Context, arg CreatePublicDashboardParams) (MetabaseDashboard, error) {
	row := q.db.QueryRowContext(ctx, createPublicDashboard,
		arg.Name,
		arg.Description,
		arg.OwnerGroup,
		arg.PublicDashboardID,
		arg.MetabaseID,
		arg.CreatedBy,
		pq.Array(arg.Keywords),
		arg.TeamkatalogenUrl,
	)
	var i MetabaseDashboard
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Group,
		&i.PublicDashboardID,
		&i.MetabaseID,
		&i.CreatedBy,
		&i.Created,
		&i.LastModified,
		&i.TsvDocument,
		pq.Array(&i.Keywords),
		&i.TeamkatalogenUrl,
	)
	return i, err
}

const deletePublicDashboard = `-- name: DeletePublicDashboard :exec
DELETE FROM metabase_dashboard
WHERE id = $1
`

func (q *Queries) DeletePublicDashboard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePublicDashboard, id)
	return err
}

const getDashboard = `-- name: GetDashboard :one
SELECT id, url
FROM "dashboards"
WHERE id = $1
`

func (q *Queries) GetDashboard(ctx context.Context, id uuid.UUID) (Dashboard, error) {
	row := q.db.QueryRowContext(ctx, getDashboard, id)
	var i Dashboard
	err := row.Scan(&i.ID, &i.Url)
	return i, err
}
