// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: team_projects_cache.sql

package gensql

import (
	"context"
)

const addTeamProject = `-- name: AddTeamProject :one
INSERT INTO team_projects ("team",
                           "group_email",
                           "project")
VALUES (
    $1,
    $2,
    $3
)
RETURNING team, project, group_email
`

type AddTeamProjectParams struct {
	Team       string
	GroupEmail string
	Project    string
}

func (q *Queries) AddTeamProject(ctx context.Context, arg AddTeamProjectParams) (TeamProject, error) {
	row := q.db.QueryRowContext(ctx, addTeamProject, arg.Team, arg.GroupEmail, arg.Project)
	var i TeamProject
	err := row.Scan(&i.Team, &i.Project, &i.GroupEmail)
	return i, err
}

const clearTeamProjectsCache = `-- name: ClearTeamProjectsCache :exec
TRUNCATE team_projects
`

func (q *Queries) ClearTeamProjectsCache(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearTeamProjectsCache)
	return err
}

const getGroupEmailFromTeamSlug = `-- name: GetGroupEmailFromTeamSlug :one
SELECT group_email
FROM team_projects
WHERE team = $1
`

func (q *Queries) GetGroupEmailFromTeamSlug(ctx context.Context, team string) (string, error) {
	row := q.db.QueryRowContext(ctx, getGroupEmailFromTeamSlug, team)
	var group_email string
	err := row.Scan(&group_email)
	return group_email, err
}

const getTeamProjectFromGroupEmail = `-- name: GetTeamProjectFromGroupEmail :one
SELECT team, project, group_email
FROM team_projects
WHERE group_email = $1
`

func (q *Queries) GetTeamProjectFromGroupEmail(ctx context.Context, groupEmail string) (TeamProject, error) {
	row := q.db.QueryRowContext(ctx, getTeamProjectFromGroupEmail, groupEmail)
	var i TeamProject
	err := row.Scan(&i.Team, &i.Project, &i.GroupEmail)
	return i, err
}

const getTeamProjects = `-- name: GetTeamProjects :many
SELECT team, project, group_email
FROM team_projects
`

func (q *Queries) GetTeamProjects(ctx context.Context) ([]TeamProject, error) {
	rows, err := q.db.QueryContext(ctx, getTeamProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamProject{}
	for rows.Next() {
		var i TeamProject
		if err := rows.Scan(&i.Team, &i.Project, &i.GroupEmail); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
