// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workstations.sql

package gensql

import (
	"context"
	"encoding/json"

	"github.com/lib/pq"
)

const createWorkstationsConfigChange = `-- name: CreateWorkstationsConfigChange :exec
INSERT INTO workstations_config_history (
    "nav_ident", 
    "workstation_config"
)
VALUES (
    $1,
    $2
)
`

type CreateWorkstationsConfigChangeParams struct {
	NavIdent          string
	WorkstationConfig json.RawMessage
}

func (q *Queries) CreateWorkstationsConfigChange(ctx context.Context, arg CreateWorkstationsConfigChangeParams) error {
	_, err := q.db.ExecContext(ctx, createWorkstationsConfigChange, arg.NavIdent, arg.WorkstationConfig)
	return err
}

const createWorkstationsOnpremAllowlistChange = `-- name: CreateWorkstationsOnpremAllowlistChange :exec
INSERT INTO workstations_onprem_allowlist_history (
    "nav_ident", 
    "hosts"
)
VALUES (
    $1,
    $2
)
`

type CreateWorkstationsOnpremAllowlistChangeParams struct {
	NavIdent string
	Hosts    []string
}

func (q *Queries) CreateWorkstationsOnpremAllowlistChange(ctx context.Context, arg CreateWorkstationsOnpremAllowlistChangeParams) error {
	_, err := q.db.ExecContext(ctx, createWorkstationsOnpremAllowlistChange, arg.NavIdent, pq.Array(arg.Hosts))
	return err
}

const createWorkstationsURLListChange = `-- name: CreateWorkstationsURLListChange :exec
INSERT INTO workstations_url_list_history (
    "nav_ident", 
    "url_list"
)
VALUES (
    $1,
    $2
)
`

type CreateWorkstationsURLListChangeParams struct {
	NavIdent string
	UrlList  string
}

func (q *Queries) CreateWorkstationsURLListChange(ctx context.Context, arg CreateWorkstationsURLListChangeParams) error {
	_, err := q.db.ExecContext(ctx, createWorkstationsURLListChange, arg.NavIdent, arg.UrlList)
	return err
}

const getLastWorkstationsOnpremAllowlistChange = `-- name: GetLastWorkstationsOnpremAllowlistChange :one
SELECT 
    id, nav_ident, created_at, hosts 
FROM workstations_onprem_allowlist_history
WHERE nav_ident = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLastWorkstationsOnpremAllowlistChange(ctx context.Context, navIdent string) (WorkstationsOnpremAllowlistHistory, error) {
	row := q.db.QueryRowContext(ctx, getLastWorkstationsOnpremAllowlistChange, navIdent)
	var i WorkstationsOnpremAllowlistHistory
	err := row.Scan(
		&i.ID,
		&i.NavIdent,
		&i.CreatedAt,
		pq.Array(&i.Hosts),
	)
	return i, err
}
