version: "2"

run:
  go: '1.22'

linters:
  default: all
  disable:
    # Linters that check comments for correctness; disallow fixme, todo, etc., missing punctuation, etc.
    - godox
    - godot
    - nolintlint

    # Linters with dubious value
    - depguard
    - tagalign
    - tagliatelle
    - err113
    - varnamelen
    - wrapcheck
    - lll
    - interfacebloat # I don't mind interfaces with >10 methods
    - ireturn # Perfectly fine to return an interface
    - testpackage # Meh
    - funlen # It is probably useful, but...
    - goconst # It is probably useful, but...

    # These linters find structures with uninitialized fields, which is useful under
    # certain conditions, but shouldn't be generally enabled.
    - exhaustruct
    - exhaustive

  settings:
    dupl:
      threshold: 400
    lll:
      line-length: 170
    gocyclo:
      min-complexity: 15
    revive:
      rules:
        - name: package-comments
          disabled: true

  exclusions:
    generated: lax
    presets: []
    rules:
      - path: (.+)_test.go
        # NOTE: We should be very careful about excluding linters for test files, as tests are
        # also code and should be held to the same standards as the rest of the code.
        # Only exclude linters that are known to be problematic for test files, or don't
        # add value.
        linters:
          - dogsled
          - funlen
          - gochecknoglobals # We use globals quite a bit in tests
          - goconst # We also repeat ourselves a bit
      - text: 'in another file for this package'
        path: '.*\.go'

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax

issues:
  # Show only new issues created after git revision
  # A long-term goal should be to fix all existing issues, and then remove this
  new-from-rev: HEAD

output:
  formats:
    text:
      colors: true
