oauth:
  client_id: # Loaded from env var AZURE_CLIENT_ID
  client_secret: # Loaded from env var AZURE_CLIENT_SECRET
  tenant_id: # Loaded from env var AZURE_TENANT_ID
  redirect_url: http://localhost:8080/api/oauth2/callback
google:
    client_id: # Loaded from env var NADA_GOOGLE_CLIENT_ID
    client_secret: # Loaded from env var NADA_GOOGLE_CLIENT_SECRET
    tenant_id: 
    redirect_url: http://localhost:8080/api/googleOauth2/callback  
    hmac_key: # Loaded from env var NADA_GOOGLE_HMAC_KEY
metabase:
  username: nada@nav.no
  password: superdupersecret1
  api_url: http://localhost:8083/api
  credentials_path: ./test-metabase-sa.json
  gcp_project: nada-dev-db2e
  databases_base_url: http://localhost:8083/browse/databases
  mapping_deadline_sec: 600 # 10 minutes
  mapping_frequency_sec: 600 # 10 minutes
  kms:
    project: nada-dev-db2e
    location: europe-north1
    keyring: datamarkedsplassen
    key_name: sa-key-encrypter
  host: http://localhost:8083
cross_team_pseudonymization:
  gcp_project_id: datamarkedsplassen-dev
  gcp_region: europe-north1
gcs:
  endpoint: http://localhost:8082/storage/v1/
  disable_auth: true
  story_bucket_name: nada-quarto-storage-dev
  central_gcp_project: datamarkedsplassen-dev
big_query:
  team_project_pseudo_views_dataset_name: markedsplassen_pseudo
  gcp_region: europe-north1
  enable_auth: true
  central_gcp_project: datamarkedsplassen-dev
slack:
  webhook_url: # Loaded from env var NADA_SLACK_WEBHOOK_URL
  token: # Loaded from env var NADA_SLACK_TOKEN
  channel_override: # no-op when dry running
  dry_run: true
server:
  hostname: localhost
  address: 0.0.0.0
  port: 8080
postgres:
  host: 127.0.0.1
  port: 5432
  user_name: nada-backend
  password: postgres
  database_name: nada
  ssl_mode: disable
  configuration:
    max_open_connections: 5
    max_idle_connections: 3
teams_catalogue:
  api_url: https://teamkatalog-api.intern.nav.no
  cache_duration_seconds: 7200
treatment_catalogue:
  api_url: https://polly.intern.dev.nav.no/process
  purpose_url: https://behandlingskatalog.intern.dev.nav.no/process/purpose
google_groups:
  impersonation_subject: johnny.horvi@nav.no
  credentials_file: ./test-sa.json
gcp:
  gcs:
    endpoint: http://localhost:8082
    story_bucket_name: nada-quarto-storage-dev
  big_query:
    team_project_pseudo_views_dataset_name: markedsplassen_pseudo_local
cookies:
  redirect:
    name: redirecturi
    max_age: 3600
    path: /
    domain: localhost
    same_site: Lax
    secure: false
    http_only: true
  oauth_state:
    name: oauthstate
    max_age: 3600
    path: /
    domain: localhost
    same_site: Lax
    secure: false
    http_only: true
  session:
    name: nada_session
    max_age: 86400
    path: /
    domain: localhost
    same_site: Lax
    secure: false
    http_only: true
nais_console:
  api_key: # Loaded from env var NADA_NAIS_CONSOLE_API_KEY
  api_url: https://console.nav.cloud.nais.io
api:
  auth_token: 1234
workstation:
  workstations_project: knada-dev
  service_accounts_project: nada-dev-db2e
  tls_secure_web_proxy_policy: secure-web-gateway-security-policy
  firewall_policy_name: onprem-access
  location: europe-north1
  clusterID: knada
  logging_bucket: knada-swp-request-logs
  logging_view: knada-swp-request-logs
  administrator_service_account: nada-backen-nada-23ow5ma@nais-dev-2e7b.iam.gserviceaccount.com
  artifact_repository_name: knast-images
  artifact_repository_project: knada-gcp
  signer_service_account: dvh-jwt-signer@knada-dev.iam.gserviceaccount.com
  stop_signal_topic: workstations-signals
  stop_signal_subscription: markedsplassen-ws-signals-sub
  knast_ad_groups:
    - 1bedf8e0-50e4-47dc-9143-23d2685159eb
    - 48120347-8582-4329-8673-7beb3ed6ca06
    - 76e9ee7e-2cd1-4814-b199-6c0be007d7b4
    - eb5c5556-6c9a-4e54-83fc-f70cae25358d
    - 8166af3f-25e5-473a-98f4-86030aa7ba27
  machine_cost_cache_duration_seconds: 86400
onprem_mapping:
  bucket: onprem-hostmap
  mapping_file: onprem-firewall-map.yaml
dvh:
  host: http://localhost:8093
  client_id: "client_id"
  client_secret: "client_secret"
pubsub:
  location: europe-north1
email_suffix: '@nav.no'
nais_cluster_name: dev-gcp
keywords_admin_group: nada@nav.no
all_users_email: all-users@nav.no
all_users_group: group:all-users@nav.no
login_page: http://localhost:3000/
cache_duration_seconds: 7200
team_projects_update_delay_seconds: 10
keep_empty_stories_for_days: 7
debug: false
log_level: info
pod_name: localhost
artifact_registry:
  cache_duration_seconds: 600
