import {
    CodeCrypto,
    CodeDatabase,
    CodeDatasetNotSynced,
    CodeExpiresInPast,
    CodeExternalEncoding,
    CodeGCPArtifactRegistry,
    CodeGCPBigQuery,
    CodeGCPCloudLogging,
    CodeGCPCloudResourceManager,
    CodeGCPComputeEngine,
    CodeGCPSecureWebProxy,
    CodeGCPServiceAccount,
    CodeGCPStorage,
    CodeGCPWorkstation,
    CodeInternalDecoding,
    CodeInternalEncoding,
    CodeMetabase,
    CodeNaisConsole, CodeNotLoggedIn,
    CodeOpeningClosedDatabase,
    CodeOpeningDatasetWithPiiTags,
    CodePolly,
    CodeSlack,
    CodeTeamKatalogen,
    CodeTeamMissing,
    CodeTransactionalQueue,
    CodeUnexpectedSubjectFormat,
    CodeUnknownHostInOnPremAllowList,
    CodeUserMissing,
    CodeWaitingForDatabase,
    CodeWrongOwner,
    ParamAccessRequest,
    ParamChannel,
    ParamDataProduct,
    ParamDataset,
    ParamDatasource,
    ParamExternalRequest,
    ParamExternalResponse,
    ParamGroupEmail,
    ParamInsightProduct,
    ParamJob,
    ParamObject,
    ParamOwner,
    ParamPiiTags,
    ParamPolicy,
    ParamPolicyRule,
    ParamPolly,
    ParamProductArea,
    ParamSchema,
    ParamServiceAccount,
    ParamStory,
    ParamTable,
    ParamTableType,
    ParamTeam,
    ParamToken,
    ParamURLList,
    ParamUser,
    ParamWorkstation
} from "../../lib/rest/generatedDto";

const codeTranslations: { [key: string]: string } = {
    [CodeGCPArtifactRegistry]: "snakket med google cloud artifact registry.",
    [CodeGCPBigQuery]: "snakket med google cloud bigquery.",
    [CodeGCPCloudLogging]: "snakket med google cloud logging.",
    [CodeGCPCloudResourceManager]: "snakket med google cloud resource manager.",
    [CodeGCPComputeEngine]: "snakket med google cloud compute engine.",
    [CodeGCPSecureWebProxy]: "snakket med google cloud secure web proxy.",
    [CodeGCPServiceAccount]: "snakket med google cloud service account.",
    [CodeGCPStorage]: "snakket med google cloud storage.",
    [CodeGCPWorkstation]: "snakket med google cloud workstation.",
    [CodeMetabase]: "snakket med Metabase.",
    [CodeNaisConsole]: "snakket med NAIS Console.",
    [CodePolly]: "snakket med Polly.",
    [CodeTeamKatalogen]: "snakket med Team Katalogen.",
    [CodeSlack]: "snakket med Slack.",
    [CodeTransactionalQueue]: "snakket med vårt kø system.",
    [CodeDatabase]: "snakket med vår database.",
    [CodeInternalDecoding]: "behandlet en intern melding.",
    [CodeInternalEncoding]: "behandlet en intern melding.",
    [CodeExternalEncoding]: "behandlet en ekstern melding.",
    [CodeCrypto]: "jobbet med kryptering.",
    [CodeOpeningDatasetWithPiiTags]: "prøvde å åpne et datasett for deg, som er tilgangsstyrt, og inneholder personopplysninger. Disse kan ikke åpnes.",
    [CodeOpeningClosedDatabase]: "prøvde å åpne en database som er tilgangsstyrt. Disse kan ikke åpnes.",
    [CodeUnexpectedSubjectFormat]: "prosesserte en forespørsel med et uventet format.",
    [CodeExpiresInPast]: "forsøkte å sette en utløpsdatoen, som er i fortiden. Du må sette den frem i tid.",
    [CodeWrongOwner]: "forsøkte å gjøre noe med en ressurs du ikke eier.",
    [CodeWaitingForDatabase]: "ventet på at en database vi oppretter for deg skal bli klar. Prøv igjen.",
    [CodeDatasetNotSynced]: "skulle endre på et datasett som ikke er synkronisert enda. Prøv igjen senere.",
    [CodeTeamMissing]: "skulle gjøre noe for deg, men team mangler.",
    [CodeUserMissing]: "skulle gjøre noe for deg, men bruker mangler",
    [CodeUnknownHostInOnPremAllowList]: "skulle legge til en host i on-prem allow-listen som ikke finnes.",
    [CodeNotLoggedIn]: "skulle gjøre noe for deg, men du må være logget inn for å gjennomføre denne handlingen.",
};

export const translateCode = (code?: string): string => {
    return code ? codeTranslations[code] || code : "ukjent :(";
};

const paramTranslations: { [key: string]: string } = {
    [ParamDataset]: "et datasett",
    [ParamAccessRequest]: "en tilgangsforespørsel",
    [ParamUser]: "en bruker",
    [ParamOwner]: "en eier",
    [ParamPiiTags]: "personopplysninger",
    [ParamDataProduct]: "et dataprodukt",
    [ParamSchema]: "et skjema",
    [ParamInsightProduct]: "et innsiktsprodukt",
    [ParamDatasource]: "en datakilde",
    [ParamGroupEmail]: "gruppe e-post",
    [ParamPolly]: "polly",
    [ParamProductArea]: "et produktområde",
    [ParamStory]: "en fortelling",
    [ParamJob]: "en jobb i en kø",
    [ParamTable]: "en tabell",
    [ParamPolicy]: "en policy",
    [ParamPolicyRule]: "en policy regel",
    [ParamURLList]: "en URL liste",
    [ParamServiceAccount]: "en service account",
    [ParamObject]: "et objekt",
    [ParamWorkstation]: "en arbeidsmaskin",
    [ParamExternalRequest]: "en ekstern forespørsel",
    [ParamExternalResponse]: "en ekstern respons",
    [ParamTeam]: "et team",
    [ParamChannel]: "en kanal",
    [ParamTableType]: "en tabell type",
    [ParamToken]: "et API token",
};

export const translateParam = (param?: string): string => {
    return param ? paramTranslations[param] || param : "ukjent :(";
};

const statusCodeTranslations: { [key: number]: string } = {
    [400]: "Du har sendt en ugyldig forespørsel.",
    [401]: "Du er ikke logget inn, eller har ikke tilgang til denne ressursen.",
    [403]: "Du har ikke tilgang til denne ressursen, på grunn av manglende rettigheter.",
    [404]: "Fant ikke ressursen.",
    [415]: "Vi støtter ikke det formatet.",
    [500]: "Noe gikk galt internt i systemet vår :(",
}

export const translateStatusCode = (statusCode?: number): string => {
    return statusCode ? statusCodeTranslations[statusCode] || "Ukjent feil" : "Ukjent feil";
};
