import {
    CodeCrypto,
    CodeDatabase,
    CodeDatasetNotSynced,
    CodeExpiresInPast,
    CodeExternalEncoding,
    CodeGCPArtifactRegistry,
    CodeGCPBigQuery,
    CodeGCPCloudLogging,
    CodeGCPCloudResourceManager,
    CodeGCPComputeEngine,
    CodeGCPSecureWebProxy,
    CodeGCPServiceAccount,
    CodeGCPStorage,
    CodeGCPWorkstation,
    CodeInternalDecoding,
    CodeInternalEncoding,
    CodeMetabase,
    CodeNaisConsole,
    CodeNotLoggedIn,
    CodeOpeningClosedDatabase,
    CodeOpeningDatasetWithPiiTags,
    CodePolly,
    CodeSlack,
    CodeTeamKatalogen,
    CodeTeamMissing,
    CodeTransactionalQueue,
    CodeUnexpectedSubjectFormat,
    CodeUnknownHostInOnPremAllowList,
    CodeUserMissing,
    CodeWaitingForDatabase,
    CodeWrongOwner,
    KindBrokenLink,
    KindDatabase,
    KindExist,
    KindInternal,
    KindInvalid,
    KindInvalidRequest,
    KindIO,
    KindNotExist,
    KindOther,
    KindPrivate,
    KindUnanticipated,
    KindUnauthenticated,
    KindUnauthorized,
    KindUnknown,
    KindUnsupportedMediaType,
    KindValidation,
    ParamAccessRequest,
    ParamChannel,
    ParamDataProduct,
    ParamDataset,
    ParamDatasource,
    ParamExternalRequest,
    ParamExternalResponse,
    ParamGroupEmail,
    ParamInsightProduct,
    ParamJob,
    ParamObject,
    ParamOwner,
    ParamPiiTags,
    ParamPolicy,
    ParamPolicyRule,
    ParamPolly,
    ParamProductArea,
    ParamSchema,
    ParamServiceAccount,
    ParamStory,
    ParamTable,
    ParamTableType,
    ParamTeam,
    ParamToken,
    ParamURLList,
    ParamUser,
    ParamWorkstation
} from "../../lib/rest/generatedDto";

const codeTranslations: { [key: string]: string } = {
    [CodeGCPArtifactRegistry]: "Problemer med google cloud artifact registry",
    [CodeGCPBigQuery]: "Problemer med google cloud bigquery",
    [CodeGCPCloudLogging]: "Problemer med google cloud logging",
    [CodeGCPCloudResourceManager]: "Problemer med google cloud resource manager",
    [CodeGCPComputeEngine]: "Problemer med google cloud compute engine",
    [CodeGCPSecureWebProxy]: "Problemer med google cloud secure web proxy",
    [CodeGCPServiceAccount]: "Problemer med google cloud service account",
    [CodeGCPStorage]: "Problemer med google cloud storage",
    [CodeGCPWorkstation]: "Problemer med google cloud workstation",
    [CodeMetabase]: "Problemer med Metabase",
    [CodeNaisConsole]: "Problemer med NAIS Console",
    [CodePolly]: "Problemer med Polly",
    [CodeTeamKatalogen]: "Problemer med Team Katalogen",
    [CodeSlack]: "Problemer med Slack",
    [CodeTransactionalQueue]: "Problemer med kø systemet vårt",
    [CodeDatabase]: "Problemer med databasen vår",
    [CodeInternalDecoding]: "Problemer med serialisering av en intern melding",
    [CodeInternalEncoding]: "Problemer med deserialisering av en intern melding",
    [CodeExternalEncoding]: "Problemer med serialisering av en ekstern melding",
    [CodeCrypto]: "Problemer med kryptering",
    [CodeOpeningDatasetWithPiiTags]: "Prøvde å åpne et datasett for deg, som er tilgangsstyrt, og inneholder personopplysninger. Disse kan ikke åpnes.",
    [CodeOpeningClosedDatabase]: "Prøvde å åpne en database som er tilgangsstyrt. Disse kan ikke åpnes.",
    [CodeUnexpectedSubjectFormat]: "Prosesserte en forespørsel med et uventet format.",
    [CodeExpiresInPast]: "Forsøkte å sette en utløpsdatoen, som er i fortiden. Du må sette den frem i tid.",
    [CodeWrongOwner]: "Forsøkte å gjøre noe med en ressurs du ikke eier.",
    [CodeWaitingForDatabase]: "Ventet på at en database vi oppretter for deg skal bli klar. Prøv igjen.",
    [CodeDatasetNotSynced]: "Skulle endre på et datasett som ikke er synkronisert enda. Prøv igjen senere.",
    [CodeTeamMissing]: "Skulle gjøre noe for deg, men team mangler.",
    [CodeUserMissing]: "Skulle gjøre noe for deg, men bruker mangler",
    [CodeUnknownHostInOnPremAllowList]: "Skulle legge til en host i on-prem allow-listen som ikke finnes.",
    [CodeNotLoggedIn]: "Skulle gjøre noe for deg, men du må være logget inn for å gjennomføre denne handlingen.",
};

export const translateCode = (code?: string): string => {
    return code ? codeTranslations[code] || code : "Ukjent kode";
};

const paramTranslations: { [key: string]: string } = {
    [ParamDataset]: "Gjelder et datasett",
    [ParamAccessRequest]: "Gjelder en tilgangsforespørsel",
    [ParamUser]: "Gjelder en bruker",
    [ParamOwner]: "Gjelder en eier",
    [ParamPiiTags]: "Gjelder personopplysninger",
    [ParamDataProduct]: "Gjelder et dataprodukt",
    [ParamSchema]: "Gjelder et dataskjema",
    [ParamInsightProduct]: "Gjelder et innsiktsprodukt",
    [ParamDatasource]: "Gjelder en datakilde",
    [ParamGroupEmail]: "Gjelder e-post medlemskap i en gruppe",
    [ParamPolly]: "Gjelder polly",
    [ParamProductArea]: "Gjelder et produktområde",
    [ParamStory]: "Gjelder en fortelling",
    [ParamJob]: "Gjelder en jobb i køsystemet",
    [ParamTable]: "Gjelder en tabell",
    [ParamPolicy]: "Gjelder en policy",
    [ParamPolicyRule]: "Gjelder en policy regel",
    [ParamURLList]: "Gjelder en URL liste",
    [ParamServiceAccount]: "Gjelder en service account",
    [ParamObject]: "Gjelder et objekt",
    [ParamWorkstation]: "Gjelder en arbeidsmaskin",
    [ParamExternalRequest]: "Gjelder en ekstern forespørsel",
    [ParamExternalResponse]: "Gjelder en ekstern respons",
    [ParamTeam]: "Gjelder et team",
    [ParamChannel]: "Gjelder en kanal",
    [ParamTableType]: "Gjelder en tabell type",
    [ParamToken]: "Gjelder et API token",
};

export const translateParam = (param?: string): string => {
    return param ? paramTranslations[param] || param : "Ukjent parameter";
};

const statusCodeTranslations: { [key: number]: string } = {
    [400]: "Du har sendt en ugyldig forespørsel.",
    [401]: "Du er ikke logget inn, eller har ikke tilgang til denne ressursen.",
    [403]: "Du har ikke tilgang til denne ressursen, på grunn av manglende rettigheter.",
    [404]: "Fant ikke ressursen.",
    [415]: "Vi støtter ikke det formatet.",
    [500]: "Noe gikk galt internt i systemet vår :(",
}

export const translateStatusCode = (statusCode?: number): string => {
    return statusCode ? statusCodeTranslations[statusCode] || "Ukjent status kode" : "Ukjent status kode";
};

const kindTranslations: { [key: string]: string } = {
    [KindOther]: "Det har skjedd en uventet feil",
    [KindInvalid]: "Operasjonen er ugyldig",
    [KindIO]: "Noe gikk galt da vi var i kontakt med eksterne systemer",
    [KindExist]: "Vi kunne ikke gjennomføre operasjonen, siden et elementet allerede eksisterer",
    [KindNotExist]: "Vi kunne ikke gjennomføre operasjonen, siden et element ikke eksisterer",
    [KindBrokenLink]: "Lenkemålet eksisterer ikke",
    [KindPrivate]: "Kunne ikke gjennomføre, og informasjon er holdt tilbake",
    [KindInternal]: "Det har skjedd en intern feil",
    [KindDatabase]: "Noe gikk galt mens vi snakket med databasen",
    [KindValidation]: "Vi klarte ikke å validere forespørselen",
    [KindUnanticipated]: "Det har skjedd en uventet feil",
    [KindInvalidRequest]: "Forepørselen er ugyldig",
    [KindUnauthenticated]: "Du må være logget inn for å gjennomføre denne handlingen",
    [KindUnauthorized]: "Du har ikke tilgang til denne ressursen",
    [KindUnsupportedMediaType]: "Vi støtter ikke det formatet",
    [KindUnknown]: "Det har skjedd en ukjent feil",
}

export const translateKind = (kind?: string): string => {
    return kind ? kindTranslations[kind] || kind : "Det har skjedd en ukjent feil";
};
