package service

import "github.com/navikt/nada-backend/pkg/errs"

const (
	CodeGCPArtifactRegistry     errs.Code = "gcp_artifact_registry"
	CodeGCPBigQuery             errs.Code = "gcp_bigquery"
	CodeGCPCloudLogging         errs.Code = "gcp_cloud_logging"
	CodeGCPCloudResourceManager errs.Code = "gcp_cloud_resource_manager"
	CodeGCPComputeEngine        errs.Code = "gcp_compute_engine"
	CodeGCPSecureWebProxy       errs.Code = "gcp_secure_web_proxy"
	CodeGCPServiceAccount       errs.Code = "gcp_service_account"
	CodeGCPStorage              errs.Code = "gcp_storage"
	CodeGCPWorkstation          errs.Code = "gcp_workstation"
	CodeGCPIAMCredentials       errs.Code = "gcp_iamcredentials"
	CodeMetabase                errs.Code = "metabase"
	CodeNaisConsole             errs.Code = "nais_console"
	CodePolly                   errs.Code = "polly"
	CodeTeamKatalogen           errs.Code = "team_katalogen"
	CodeSlack                   errs.Code = "slack"
	CodeTransactionalQueue      errs.Code = "transactional_queue"
	CodeDatabase                errs.Code = "database"
	CodeInternalDecoding        errs.Code = "internal_decoding"
	CodeInternalEncoding        errs.Code = "internal_encoding"
	CodeExternalEncoding        errs.Code = "external_encoding"
	CodeCrypto                  errs.Code = "crypto"

	CodeOpeningDatasetWithPiiTags    errs.Code = "opening_dataset_with_pii_tags"
	CodeOpeningClosedDatabase        errs.Code = "opening_closed_database"
	CodeUnexpectedSubjectFormat      errs.Code = "subject_format"
	CodeExpiresInPast                errs.Code = "expires_in_past"
	CodeWrongOwner                   errs.Code = "wrong_owner"
	CodeWaitingForDatabase           errs.Code = "waiting_for_database"
	CodeDatasetNotSynced             errs.Code = "dataset_not_synced"
	CodeTeamMissing                  errs.Code = "team_missing"
	CodeUserMissing                  errs.Code = "user_missing"
	CodeUnknownHostInOnPremAllowList errs.Code = "unknown_host_in_on_prem_allow_list"
	CodeNotLoggedIn                  errs.Code = "not_logged_in"
)

const (
	ParamDataset          errs.Parameter = "dataset"
	ParamAccessRequest    errs.Parameter = "access_request"
	ParamUser             errs.Parameter = "user"
	ParamOwner            errs.Parameter = "owner"
	ParamPiiTags          errs.Parameter = "pii_tags"
	ParamDataProduct      errs.Parameter = "data_product"
	ParamSchema           errs.Parameter = "schema"
	ParamInsightProduct   errs.Parameter = "insight_product"
	ParamDatasource       errs.Parameter = "datasource"
	ParamGroupEmail       errs.Parameter = "group_email"
	ParamPolly            errs.Parameter = "polly"
	ParamProductArea      errs.Parameter = "product_area"
	ParamStory            errs.Parameter = "story"
	ParamJob              errs.Parameter = "job"
	ParamTable            errs.Parameter = "table"
	ParamPolicy           errs.Parameter = "policy"
	ParamPolicyRule       errs.Parameter = "policy_rule"
	ParamURLList          errs.Parameter = "url_list"
	ParamServiceAccount   errs.Parameter = "service_account"
	ParamObject           errs.Parameter = "object"
	ParamWorkstation      errs.Parameter = "workstation"
	ParamExternalRequest  errs.Parameter = "external_request"
	ParamExternalResponse errs.Parameter = "external_response"
	ParamTeam             errs.Parameter = "team"
	ParamChannel          errs.Parameter = "channel"
	ParamTableType        errs.Parameter = "table_type"
	ParamToken            errs.Parameter = "token"
)

const (
	KindOther                string = "other_error"
	KindInvalid              string = "invalid_operation"
	KindIO                   string = "io_error"
	KindExist                string = "item_exists"
	KindNotExist             string = "item_not_exist"
	KindBrokenLink           string = "link_target_not_exist"
	KindPrivate              string = "information_withheld"
	KindInternal             string = "internal_error"
	KindDatabase             string = "database_error"
	KindValidation           string = "input_validation_error"
	KindUnanticipated        string = "unanticipated_error"
	KindInvalidRequest       string = "invalid_request_error"
	KindUnauthenticated      string = "unauthenticated_request"
	KindUnauthorized         string = "unauthorized_request"
	KindUnsupportedMediaType string = "unsupported_media_type"
	KindUnknown              string = "unknown_error_kind"
)
