package service

import "github.com/navikt/nada-backend/pkg/errs"

const (
	CodeGCPArtifactRegistry     = errs.Code("gcp_artifact_registry")
	CodeGCPBigQuery             = errs.Code("gcp_bigquery")
	CodeGCPCloudLogging         = errs.Code("gcp_cloud_logging")
	CodeGCPCloudResourceManager = errs.Code("gcp_cloud_resource_manager")
	CodeGCPComputeEngine        = errs.Code("gcp_compute_engine")
	CodeGCPSecureWebProxy       = errs.Code("gcp_secure_web_proxy")
	CodeGCPServiceAccount       = errs.Code("gcp_service_account")
	CodeGCPStorage              = errs.Code("gcp_storage")
	CodeGCPWorkstation          = errs.Code("gcp_workstation")
	CodeMetabase                = errs.Code("metabase")
	CodeNaisConsole             = errs.Code("nais_console")
	CodePolly                   = errs.Code("polly")
	CodeTeamKatalogen           = errs.Code("team_katalogen")
	CodeSlackNotification       = errs.Code("slack_notification")
	CodeTransactionalQueue      = errs.Code("transactional_queue")
	CodeDatabase                = errs.Code("database")
	CodeInternalDecoding        = errs.Code("internal_decoding")
	CodeInternalEncoding        = errs.Code("internal_encoding")
	CodeExternalEncoding        = errs.Code("external_encoding")
	CodeCrypto                  = errs.Code("CRYPTO")
)

const (
	ParamDataset          = errs.Parameter("dataset")
	ParamAccessRequest    = errs.Parameter("access_request")
	ParamUser             = errs.Parameter("user")
	ParamOwner            = errs.Parameter("owner")
	ParamPiiTags          = errs.Parameter("pii_tags")
	ParamDataProduct      = errs.Parameter("data_product")
	ParamSchema           = errs.Parameter("schema")
	ParamInsightProduct   = errs.Parameter("insight_product")
	ParamDatasource       = errs.Parameter("datasource")
	ParamGroupEmail       = errs.Parameter("group_email")
	ParamPolly            = errs.Parameter("polly")
	ParamProductArea      = errs.Parameter("product_area")
	ParamStory            = errs.Parameter("story")
	ParamJob              = errs.Parameter("job")
	ParamTable            = errs.Parameter("table")
	ParamPolicy           = errs.Parameter("policy")
	ParamPolicyRule       = errs.Parameter("policy_rule")
	ParamURLList          = errs.Parameter("url_list")
	ParamServiceAccount   = errs.Parameter("service_account")
	ParamObject           = errs.Parameter("object")
	ParamWorkstation      = errs.Parameter("workstation")
	ParamExternalRequest  = errs.Parameter("external_request")
	ParamExternalResponse = errs.Parameter("external_response")
	ParamTeam             = errs.Parameter("team")
)
