apiVersion: v1
kind: ConfigMap
metadata:
  name: log-config
  namespace: nada
data:
  log-layout.json: |
    {
      "timestamp": {
        "$resolver": "timestamp",
        "format": "yyyy-MM-dd'T'HH:mm:ss.SSSZ",
        "timeZone": "UTC"
      },
      "source_host": "${hostName}",
      "level": {
        "$resolver": "level",
        "field": "name"
      },
      "logger_name": {
        "$resolver": "logger",
        "field": "name"
      },
      "message": {
        "$resolver": "message",
        "stringified": true
      },
      "mdc": {
        "$resolver": "mdc"
      },
      "exception": {
        "exception_class": {
          "$resolver": "exception",
          "field": "className"
        },
        "exception_message": {
          "$resolver": "exception",
          "field": "message"
        },
        "stacktrace": {
          "$resolver": "exception",
          "field": "stackTrace",
          "stackTrace": {
            "stringified": true
          }
        }
      }
    }
  log-config.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration>
      <Appenders>
        <Console name="STDOUT" target="SYSTEM_OUT" follow="true">
          <JsonTemplateLayout eventTemplateUri="file:////home/metabase/log-layout.json">
          </JsonTemplateLayout>
        </Console>
      </Appenders>
      <Loggers>
        <Logger name="com.mchange" level="ERROR"/>
        <Logger name="liquibase" level="ERROR"/>
        <Logger name="metabase" level="INFO"/>
        <Logger name="metabase-enterprise" level="INFO"/>
        <Logger name="metabase.metabot" level="DEBUG"/>
        <Logger name="metabase.plugins" level="DEBUG"/>
        <Logger name="metabase.query-processor.async" level="DEBUG"/>
        <Logger name="metabase.server.middleware" level="DEBUG"/>
        <Logger name="org.quartz" level="INFO"/>
        <Logger name="net.snowflake.client.jdbc.SnowflakeConnectString" level="ERROR"/>
        <Root level="WARN">
          <AppenderRef ref="STDOUT"/>
        </Root>
      </Loggers>
    </Configuration>