apiVersion: v1
kind: ConfigMap
metadata:
  name: log-config
data:
  log-layout.json: |
    {
      "timestamp": {
        "$resolver": "timestamp",
        "format": "yyyy-MM-dd'T'HH:mm:ss.SSSZ",
        "timeZone": "UTC"
      },
      "source_host": "${hostName}",
      "level": {
        "$resolver": "level",
        "field": "name"
      },
      "logger_name": {
        "$resolver": "logger",
        "field": "name"
      },
      "message": {
        "$resolver": "message",
        "stringified": true
      },
      "mdc": {
        "$resolver": "mdc"
      },
      "exception": {
        "exception_class": {
          "$resolver": "exception",
          "field": "className"
        },
        "exception_message": {
          "$resolver": "exception",
          "field": "message"
        },
        "stacktrace": {
          "$resolver": "exception",
          "field": "stackTrace",
          "stackTrace": {
            "stringified": true
          }
        }
      }
    }