FROM golang:1.24-bookworm AS bqbuilder

RUN apt-get update && apt-get install -y --no-install-recommends clang

ENV CGO_ENABLED=1
ENV CXX=clang++

WORKDIR /src
COPY ../../.. .
RUN mkdir -p /app/bin
RUN go build -o /app/bin/bq ./cmd/bq/main.go

FROM golang:1.24-bookworm AS builder

WORKDIR /src
COPY ../../.. .
RUN mkdir -p /app/bin
RUN go build -o /app/bin/nc ./cmd/nc/main.go
RUN go build -o /app/bin/tk ./cmd/tk/main.go
RUN go build -o /app/bin/sa ./cmd/sa/main.go
RUN go build -o /app/bin/ws ./cmd/ws/main.go
RUN go build -o /app/bin/swp ./cmd/swp/main.go
RUN go build -o /app/bin/crm ./cmd/crm/main.go

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/bin /app/bin
COPY --from=bqbuilder /app/bin/bq /app/bin/bq
