name: Codecov

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  codecov:
    name: Code Coverage
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/1007056531311/locations/global/workloadIdentityPools/ci-nada-prod/providers/ci-nada-prod
          service_account: ci-nada-images@nada-prod-6977.iam.gserviceaccount.com

      - uses: docker/login-action@v3
        name: Login to Google Artifact Registry
        with:
          registry: europe-north1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - id: store-metabase-test-credentials
        run: |
          cat << 'EOF' > tests-metabase-all-users-sa-creds.json
          ${{ secrets.METABASE_ALL_USERS_SA_CREDS_JSON }}
          EOF

      - name: Run tests with coverage
        run: make cover
        env:
          RIVER_PRO_SECRET: ${{ secrets.RIVER_PRO_SECRET }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
