apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: nada-frontend
  namespace: nada
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100M
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
  labels:
    team: nada
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - https://data.intern.dev.nav.no
    - https://data.ansatt.dev.nav.no
  redirects:
    - from: https://data.intern.dev.nav.no
      to: https://data.ansatt.dev.nav.no
  accessPolicy:
    outbound:
      rules:
        - application: nada-backend
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: nav.no
    sidecar:
      enabled: true
      autoLogin: true
  env:
    - name: NADA_BACKEND_SCOPE
      value: api://dev-gcp.nada.nada-backend/.default
