apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: nada-frontend
  namespace: nada
  labels:
    team: nada
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - https://data.intern.dev.nav.no
    - https://data.ansatt.dev.nav.no
  redirects:
    - from: https://data.intern.dev.nav.no
      to: https://data.ansatt.dev.nav.no
  accessPolicy:
    outbound:
      rules:
        - application: nada-backend
  azure:
    application:
      enabled: true
      allowAllUsers: true
    sidecar:
      enabled: true
      autoLogin: true
